/**
 * TypeScript interfaces for spatial network data
 * Generated by generate_spatial_networks.py
 */

/** A node in the spatial network representing a location */
export interface NetworkNode {
	/** Unique identifier (format: "location:{id}") */
	id: string;
	/** Node type (always "location" for spatial networks) */
	type: 'location';
	/** Display label (location name) */
	label: string;
	/** Number of articles mentioning this location */
	count: number;
	/** GPS coordinates [latitude, longitude] */
	coordinates: [number, number];
	/** Country name */
	country: string;
	/** Region name */
	region: string;
	/** Prefecture name */
	prefecture: string;
	/** Array of related article IDs */
	relatedArticleIds: string[];
	/** Network degree (number of connections) */
	degree: number;
	/** Network strength (sum of edge weights) */
	strength: number;
}

/** An edge in the spatial network representing co-occurrence between locations */
export interface NetworkEdge {
	/** Source node ID */
	source: string;
	/** Target node ID */
	target: string;
	/** Number of articles where both locations co-occur */
	weight: number;
	/** Normalized weight (0-1) */
	weightNorm: number;
	/** Array of article IDs where co-occurrence happens */
	articleIds: string[];
}

/** Geographic bounds for the network */
export interface NetworkBounds {
	/** Northern latitude boundary */
	north: number;
	/** Southern latitude boundary */
	south: number;
	/** Eastern longitude boundary */
	east: number;
	/** Western longitude boundary */
	west: number;
}

/** Metadata about the network generation */
export interface NetworkMeta {
	/** ISO timestamp of generation */
	generatedAt: string;
	/** Total number of nodes */
	totalNodes: number;
	/** Total number of edges */
	totalEdges: number;
	/** Minimum edge weight threshold used */
	weightMin: number;
	/** Number of locations with valid coordinates */
	geocodedLocations: number;
	/** Total locations in source data */
	totalLocationsInData: number;
	/** Percentage of locations successfully geocoded */
	geocodingSuccessRate: number;
	/** Geographic bounds of the network */
	bounds: NetworkBounds | null;
	/** Number of articles with multiple locations */
	articlesWithMultipleLocations: number;
}

/** Complete spatial network data structure */
export interface SpatialNetworkData {
	/** Array of location nodes */
	nodes: NetworkNode[];
	/** Array of co-occurrence edges */
	edges: NetworkEdge[];
	/** Geographic bounds for map initialization */
	bounds: NetworkBounds | null;
	/** Generation metadata and statistics */
	meta: NetworkMeta;
}

/** Entity types in the global network */
export type EntityType = 'person' | 'organization' | 'event' | 'subject' | 'location' | 'topic' | 'article' | 'author';

/** Node structure for global network (multi-entity) */
export interface GlobalNetworkNode {
	id: string;
	type: EntityType;
	label: string;
	count: number;
	degree: number;
	strength: number;
	labelPriority: number;
	/** Optional Omeka o:id for linking to islam.zmo.de */
	o_id?: string;
}

/** Edge structure for global network */
export interface GlobalNetworkEdge {
	source: string;
	target: string;
	type: string; // e.g. "person-organization"
	weight: number;
	weightNorm: number;
	articleIds: string[];
}

/** Metadata for global network */
export interface GlobalNetworkMeta {
	generatedAt: string;
	totalNodes: number;
	totalEdges: number;
	supportedTypes: EntityType[];
	weightMinConfigured: number;
	weightMinActual: number;
	weightMax: number;
	degree: { min: number; max: number; mean: number };
	strength: { min: number; max: number; mean: number };
	topLabelCount: number;
	typePairs: [string, string][];
	labelPriorityTop: string[];
}

/** Complete global network data structure */
export interface GlobalNetworkData {
	nodes: GlobalNetworkNode[];
	edges: GlobalNetworkEdge[];
	meta: GlobalNetworkMeta;
}

/** View mode for network visualization */
export type NetworkViewMode = 'graph' | 'map';

/** Node size scaling options */
export type NodeSizeBy = 'count' | 'degree' | 'strength';

/** Edge display options */
export interface EdgeDisplayOptions {
	/** Minimum weight to display */
	minWeight: number;
	/** Whether to show edge labels */
	showLabels: boolean;
	/** Edge opacity (0-1) */
	opacity: number;
}
