/**
 * TypeScript interfaces for topic network data
 * Generated by generate_topic_network.py
 */

/** Node types in the topic network */
export type TopicNetworkNodeType = 'topic' | 'article';

/** Base properties shared by all nodes */
interface TopicNetworkNodeBase {
	/** Unique identifier (format: "topic:{id}" or "article:{id}") */
	id: string;
	/** Node type */
	type: TopicNetworkNodeType;
	/** Display label */
	label: string;
	/** Network degree (number of connections) */
	degree: number;
	/** Network strength (sum of edge weights) */
	strength: number;
	/** Label display priority (lower = more important) */
	labelPriority: number;
}

/** A topic node in the network */
export interface TopicNetworkTopicNode extends TopicNetworkNodeBase {
	type: 'topic';
	/** Number of articles assigned to this topic */
	count: number;
	/** Keywords extracted from topic label */
	keywords: string[];
}

/** An article node in the network */
export interface TopicNetworkArticleNode extends TopicNetworkNodeBase {
	type: 'article';
	/** Topic assignment probability (0-1) */
	topicProb: number;
	/** Country of origin */
	country: string;
	/** Newspaper name */
	newspaper: string;
	/** Publication date (ISO format) */
	pubDate: string;
	/** URL to the original article */
	url: string;
	/** Topic ID this article belongs to */
	topicId: number;
}

/** Union type for all node types */
export type TopicNetworkNode = TopicNetworkTopicNode | TopicNetworkArticleNode;

/** An edge in the topic network */
export interface TopicNetworkEdge {
	/** Source node ID (usually topic) */
	source: string;
	/** Target node ID (usually article) */
	target: string;
	/** Edge weight (topic probability) */
	weight: number;
	/** Normalized weight (0-1) */
	weightNorm: number;
}

/** Metadata about the network generation */
export interface TopicNetworkMeta {
	/** ISO timestamp of generation */
	generatedAt: string;
	/** Total number of nodes */
	totalNodes: number;
	/** Number of topic nodes */
	totalTopics: number;
	/** Number of article nodes */
	totalArticles: number;
	/** Total number of edges */
	totalEdges: number;
	/** Maximum articles sampled per topic */
	articlesPerTopic: number;
	/** Minimum topic probability threshold used */
	minTopicProb: number;
	/** Average topic probability across all edges */
	avgTopicProb: number;
	/** Minimum edge weight */
	weightMin: number;
	/** Maximum edge weight */
	weightMax: number;
}

/** Complete topic network data structure */
export interface TopicNetworkData {
	/** Array of topic and article nodes */
	nodes: TopicNetworkNode[];
	/** Array of topic-article edges */
	edges: TopicNetworkEdge[];
	/** Generation metadata and statistics */
	meta: TopicNetworkMeta;
}

/** Type guards for node types */
export function isTopicNode(node: TopicNetworkNode): node is TopicNetworkTopicNode {
	return node.type === 'topic';
}

export function isArticleNode(node: TopicNetworkNode): node is TopicNetworkArticleNode {
	return node.type === 'article';
}
