name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

  # Allow manual trigger
  workflow_dispatch:

# Set GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate IWAC data
        run: |
          pip install -r scripts/requirements.txt
          cd scripts
          python generate_treemap.py --output-dir ../static/data
          python generate_wordcloud.py --output-dir ../static/data
          python generate_language_facets.py --output-dir ../static/data
          python generate_index_entities.py --output-dir ../static/data
          python generate_categories.py --output-dir ../static/data
          python generate_timeline.py --output-dir ../static/data
          python generate_overview_stats.py --output-dir ../static/data
          cd ..
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Build SvelteKit app
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
